### ISSUE TITLE
JSON Decode Error running main.py in Powershell 5 and CMD

### ISSUE THREAD

**Issue by michaelpkuhn** [Code-For-Chicago/greater-chicago-food-despository#19]
```
Traceback (most recent call last):
  File "src/main.py", line 78, in <module>
    main()
  File "src/main.py", line 71, in main
    d_ls = censusData(geo_ls)
  File "src/main.py", line 57, in censusData
    d_ls += c.getData()
  File "src/main.py", line 25, in getData
    c_ls = getCensusData(self.var_dict, self.table, self.function_ls, self.geo_ls)
  File "PATH\greater-chicago-food-despository\src\census_response.py", line 61, in getCensusData
    response_data = response.json()
  File "PATH\Anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "PATH\Anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "PATH\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "PATH\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

- Attempted passing encoding utf8 and utf16 to response.json()
- Did not attempt Powershell 6+
- Believed to be related to Powershell/MS encoding [[1](https://stackoverflow.com/questions/37488748/python-3-not-reading-a-json-file-right/37489223)][[2](https://old.reddit.com/r/learnpython/comments/2iptr3/unicode_encoding_error_when_printing_html_requests/)]

Until fixed, Windows users recommended to use Git Bash or similar shell

**Comment by michaelpkuhn** [comment]
This error occurs when code is run without an API key
